# Generated by Django 4.2.7 on 2023-11-05 00:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cur_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cur_longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fav_location',
            field=models.CharField(choices=[('Robarts', 'Robarts'), ('University College Library', 'University College Library'), ('Sandford Fleming Library', 'Sandford Fleming Library'), ('Knox College Library', 'Knox College Library'), ('Bahen', 'Bahen'), ('Myhal', 'Myhal'), ('Hart House', 'Hart House')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends_list',
            field=models.ManyToManyField(blank=True, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Unspecified', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sports', 'Sports'), ('animals', 'Animals'), ('movies', 'Movies'), ('gaming', 'Gaming'), ('music', 'Music'), ('literature', 'Literature'), ('magic', 'Magic'), ('cooking', 'Cooking'), ('hiking', 'Hiking'), ('gym and fitness', 'Gym And Fitness'), ('dance', 'Dance'), ('technology', 'Technology'), ('fashion', 'Fashion'), ('photography', 'Photography'), ('travel', 'Travel'), ('arts and crafts', 'Arts And Crafts'), ('knitting', 'Knitting'), ('pottery', 'Pottery'), ('volunteering', 'Volunteering'), ('skiing and snowboarding', 'Skiing And Snowboarding'), ('robotics', 'Robotics'), ('coding', 'Coding')], default='Unspecified', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('business', 'Business'), ('physics', 'Physics'), ('math', 'Math'), ('science', 'Science'), ('political science', 'Political Science'), ('nursing', 'Nursing'), ('life_science', 'Life Science'), ('health science', 'Health Science'), ('arts', 'Arts'), ('computer science', 'Computer Science'), ('humanities', 'Humanities'), ('social sciences', 'Social Sciences')], default='Unspecified', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='negative_users',
            field=models.ManyToManyField(blank=True, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='positive_users',
            field=models.ManyToManyField(blank=True, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='same_gender_pref',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], default=0),
        ),
    ]
